server:
  port: 9420
  servlet:
    context-path: /meet
    # 中文字符集
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  profiles:
    active:
    - dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*Mapper.xml

nacos:
  config:
    bootstrap:
      enable: true
    data-id: meet-config
    group: meet
    type: yaml
    auto-refresh: true
