server:
  port: 8080
  servlet:
    context-path: /meet
    
spring:
  profiles:
    active:
    - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcv123321AZ
    url: jdbc:mysql://162.14.101.164:3306/meet_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:com/pwc/sdc/**/dao/**/mapper/**/*.xml
    
nacos:
  config:
    bootstrap:
      enable: true
    data-id: meet-config
    group: meet
    type: yaml
    auto-refresh: true
